replicaCount: 1
image:
  repository: haulrest/diveargo-fastapi
  pullPolicy: IfNotPresent
  tag: "none"
nameOverride: ""
fullnameOverride: "dive-argo-fastapi"
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - paths:
        - path: /
          pathType: Prefix
nodeSelector:
  kubernetes.io/hostname: k3s-worker-1
selectorLabels: {}
